# Generated by Django 6.1 on 2026-08-25 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboundWhatsAppEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wamid', models.CharField(help_text='Meta message ID for dedup', max_length=255, unique=True)),
                ('from_number', models.CharField(help_text='Sender phone in E.164', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['wamid'], name='whatsapp_in_wamid_e2f36f_idx'), models.Index(fields=['from_number'], name='whatsapp_in_from_nu_f99295_idx'), models.Index(fields=['received_at'], name='whatsapp_in_receive_748983_idx')],
            },
        ),
    ]
