# Generated by Django 6.1 on 2026-08-25 08:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('external_event_id', models.CharField(max_length=255)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('DUPLICATE', 'Duplicate Ignored')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'unique_together': {('provider', 'external_event_id')},
            },
        ),
    ]
