# Generated by Django 6.1 on 2026-08-25 08:59

import apps.payments.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_token', models.CharField(default=apps.payments.models.generate_public_token, max_length=64, unique=True)),
                ('amount_minor', models.IntegerField(help_text='Amount in KES integer shillings or minor units')),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('reference', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('provider_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='merchants.paymentprovideraccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='MPESA_SANDBOX', max_length=50)),
                ('external_reference', models.CharField(blank=True, default='', max_length=255)),
                ('customer_phone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending User Action'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout')], default='INITIATED', max_length=20)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='tenants.tenant')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payments.paymentrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_minor', models.IntegerField()),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('mpesa_receipt_number', models.CharField(max_length=100, unique=True)),
                ('customer_phone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('SUCCEEDED', 'Succeeded'), ('REFUNDED', 'Refunded')], default='SUCCEEDED', max_length=20)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentattempt')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.paymentrequest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tenants.tenant')),
            ],
        ),
    ]
