# Generated by Django 6.1 on 2026-08-25 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flow', models.CharField(choices=[('NONE', 'None'), ('CREATE_REQUEST', 'Creating Payment Request'), ('CANCEL_REQUEST', 'Cancelling Payment Request'), ('STEP_UP_PENDING', 'Step-Up Challenge Pending'), ('PHONE_BIND', 'Phone Binding OTP')], default='NONE', max_length=20)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedWhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wamid', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
