# Generated by Django 6.1 on 2026-08-25 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversation', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='phone_identity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_session', to='identity.phoneidentity'),
        ),
        migrations.AddIndex(
            model_name='processedwhatsappmessage',
            index=models.Index(fields=['wamid'], name='conversatio_wamid_ab7400_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['phone_identity'], name='conversatio_phone_i_35800d_idx'),
        ),
    ]
