# Generated by Django 6.1 on 2026-08-25 08:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('prefix', models.CharField(max_length=12)),
                ('key_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('settlement_type', models.CharField(choices=[('PAYBILL', 'M-Pesa PayBill'), ('TILL', 'M-Pesa Buy Goods Till'), ('BANK', 'Bank Account')], default='PAYBILL', max_length=20)),
                ('settlement_number', models.CharField(help_text='PayBill No, Till No, or Bank Acc No', max_length=100)),
                ('settlement_bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING_VERIFICATION', 'Pending Verification'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=30)),
                ('kyc_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentProviderAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(default='MPESA_SANDBOX', max_length=50)),
                ('account_reference', models.CharField(max_length=100)),
                ('credentials', models.JSONField(blank=True, default=dict, help_text='Encrypted or structured provider settings')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_accounts', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number_id', models.CharField(blank=True, default='', max_length=100)),
                ('display_phone_number', models.CharField(blank=True, default='', max_length=50)),
                ('waba_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('PENDING', 'Pending Setup'), ('DISCONNECTED', 'Disconnected')], default='PENDING', max_length=20)),
                ('access_token', models.TextField(blank=True, default='')),
                ('auto_send_receipts', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_account', to='tenants.tenant')),
            ],
        ),
    ]
