# Generated by Django 6.1 on 2026-08-25 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('STAFF', 'Staff')], default='OWNER', max_length=10)),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='PENDING_VERIFICATION', max_length=25)),
                ('bound_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('pending_otp_hash', models.CharField(blank=True, default='', max_length=128)),
                ('otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bound_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_phone_identities', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_phone_identities', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_identities', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Phone Identity',
                'verbose_name_plural': 'Phone Identities',
            },
        ),
        migrations.CreateModel(
            name='StepUpChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('REMOVE_STAFF_NUMBER', 'Remove Staff Number'), ('CHANGE_SETTLEMENT_ACCOUNT', 'Change Settlement Account'), ('REFUND', 'Refund'), ('CANCEL_INFLIGHT', 'Cancel In-Flight Payment'), ('VIEW_AUDIT_LOG', 'View Audit Log')], max_length=30)),
                ('action_payload', models.JSONField(default=dict)),
                ('token_hash', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_up_challenges', to='identity.phoneidentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_up_challenges', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MagicLinkToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('purpose', models.CharField(choices=[('REPORT_VIEW', 'Report View'), ('SETTINGS_VIEW', 'Settings View'), ('STEP_UP_CONFIRM', 'Step-Up Confirmation'), ('PHONE_BIND_CONFIRM', 'Phone Bind Confirmation')], max_length=20)),
                ('scope', models.JSONField(default=dict)),
                ('single_use', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_link_tokens', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant'], name='identity_ma_tenant__9315a0_idx'), models.Index(fields=['token_hash'], name='identity_ma_token_h_431399_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='phoneidentity',
            index=models.Index(fields=['tenant'], name='identity_ph_tenant__8b4088_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneidentity',
            index=models.Index(fields=['phone_number'], name='identity_ph_phone_n_fc3811_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneidentity',
            index=models.Index(fields=['status'], name='identity_ph_status_08495c_idx'),
        ),
        migrations.AddIndex(
            model_name='stepupchallenge',
            index=models.Index(fields=['tenant'], name='identity_st_tenant__63060e_idx'),
        ),
        migrations.AddIndex(
            model_name='stepupchallenge',
            index=models.Index(fields=['token_hash'], name='identity_st_token_h_39deee_idx'),
        ),
        migrations.AddIndex(
            model_name='stepupchallenge',
            index=models.Index(fields=['status', 'expires_at'], name='identity_st_status_b83904_idx'),
        ),
    ]
